#!/bin/bash

cd ~/projects/weather

export CLASSPATH=/home/peter/lib/apache/derby/db-derby-10.15.1.3-bin/lib/derby.jar:/home/peter/lib/apache/derby/db-derby-10.15.1.3-bin/lib/derbytools.jar:.
echo $CLASSPATH

export JFX_PATH=/home/peter/lib/javafx/javafx-sdk-12.0.2/lib/
echo $JFX_PATH

java -classpath $CLASSPATH:target/weather-1.0-SNAPSHOT.jar --module-path $JFX_PATH --add-modules javafx.controls,javafx.fxml io.javasmithy.App 